services:
  watidy_landing_page_2:
    build:
      context: .
      target: production
    restart: unless-stopped

    ports:
      - 3002:3002
    environment:
      - TZ=America/Sao_Paulo
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lead.rule=Host(`lead.watidy.com.br`)"
      - "traefik.http.routers.lead.entrypoints=websecure"
      - "traefik.http.routers.lead.tls.certresolver=letsencrypt"
      - "traefik.http.services.lead.loadbalancer.server.port=3002" # ou porta que seu frontend usa
    expose:
      - 3002
    networks:
      - web

networks:
  web:
    external: true
